apiVersion: v2
appVersion: "1.0"
description: Matomo helm chart
name: matomo
icon: "https://bitnami.com/assets/stacks/matomo/img/matomo-stack-110x117.png"
version: 1.0.6-alpha4.2.1
dependencies:
  - name: mariadb
    version: 9.2.5
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.deployChart
